/**
 * Codex home resolution and per-agent auth-wrapper generation.
 *
 * The plugin reconciles a managed provider block inside the effective Codex
 * home's `config.toml` and generates a private executable wrapper that invokes
 * the packaged credential helper with the embedded agent directory and profile
 * id. The TOML references only the wrapper path, never the credential.
 *
 * Design.md § Codex Runtime Bridge, subsections 3 (home selection) and 4
 * (credential helper wrapper).
 */

import fs from "node:fs";
import os from "node:os";
import path from "node:path";

/**
 * Resolve the effective Codex home directory.
 *
 * Precedence mirrors Codex's public behavior:
 * 1. agent scope: `<agentDir>/codex-home` when an agent directory is known;
 * 2. user scope: `CODEX_HOME` env when set;
 * 3. fallback: `~/.codex`.
 *
 * User-home scope is safe because each agent/profile pair gets a distinct
 * provider id and wrapper, so shared user config is never overwritten.
 *
 * @param agentDir - Resolved agent directory, or undefined.
 * @param env - Environment map (defaults to `process.env`).
 */
export function resolveCodexHome(
  agentDir: string | undefined,
  env: NodeJS.ProcessEnv = process.env,
): string {
  if (agentDir && agentDir.trim() !== "") {
    return path.join(agentDir, "codex-home");
  }
  const envHome = env.CODEX_HOME?.trim();
  if (envHome) {
    return envHome;
  }
  return path.join(os.homedir(), ".codex");
}

/** Absolute path to the `config.toml` inside a Codex home. */
export function codexConfigPath(codexHome: string): string {
  return path.join(codexHome, "config.toml");
}

/**
 * Directory under the Codex home where the plugin stores its generated
 * per-agent auth wrappers. Kept separate from user files.
 */
export function codexWrapperDir(codexHome: string): string {
  return path.join(codexHome, "axonhub-openclaw-auth");
}

/** Absolute path to the generated wrapper for a given provider id. */
export function codexWrapperPath(codexHome: string, providerId: string): string {
  const ext = process.platform === "win32" ? ".cmd" : ".sh";
  return path.join(codexWrapperDir(codexHome), `${providerId}${ext}`);
}

/** Options for generating the per-agent credential wrapper. */
export type WrapperOptions = {
  /** Codex provider id (used to name the wrapper file). */
  providerId: string;
  /** Absolute path to the packaged credential helper (dist/codex-auth-helper.js). */
  helperPath: string;
  /** Agent directory embedded into the wrapper. */
  agentDir: string;
  /** Optional auth profile id embedded into the wrapper. */
  profileId?: string;
  /** Node executable to invoke. Defaults to `process.execPath`. */
  nodePath?: string;
};

/** Quote a value for safe embedding inside a POSIX single-quoted shell string. */
function shSingleQuote(value: string): string {
  // Close quote, insert an escaped single quote, reopen: '\'' pattern.
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/** Build the POSIX shell wrapper script text. */
function buildPosixWrapper(opts: WrapperOptions): string {
  const node = opts.nodePath ?? process.execPath;
  const parts = [
    shSingleQuote(node),
    shSingleQuote(opts.helperPath),
    shSingleQuote(opts.agentDir),
  ];
  if (opts.profileId && opts.profileId.trim() !== "") {
    parts.push(shSingleQuote(opts.profileId));
  }
  return `#!/bin/sh\n# Generated by axonhub-openclaw-plugin. Do not edit.\nexec ${parts.join(" ")}\n`;
}

/** Quote a value for a Windows batch script argument. */
function cmdQuote(value: string): string {
  return `"${value.replace(/"/g, '""')}"`;
}

/** Build the Windows batch wrapper script text. */
function buildWindowsWrapper(opts: WrapperOptions): string {
  const node = opts.nodePath ?? process.execPath;
  const parts = [cmdQuote(node), cmdQuote(opts.helperPath), cmdQuote(opts.agentDir)];
  if (opts.profileId && opts.profileId.trim() !== "") {
    parts.push(cmdQuote(opts.profileId));
  }
  return `@echo off\r\nREM Generated by axonhub-openclaw-plugin. Do not edit.\r\n${parts.join(" ")} %*\r\n`;
}

/** Build the wrapper script text for the current platform. */
export function buildWrapperScript(opts: WrapperOptions): string {
  return process.platform === "win32"
    ? buildWindowsWrapper(opts)
    : buildPosixWrapper(opts);
}

/**
 * Generate (or update) the private executable wrapper for a provider id inside
 * the Codex home. The wrapper is written with mode `0700` and invokes the
 * packaged helper with the embedded agent directory and optional profile id.
 *
 * @returns the absolute wrapper path.
 */
export function writeCodexAuthWrapper(
  codexHome: string,
  opts: WrapperOptions,
): string {
  const dir = codexWrapperDir(codexHome);
  fs.mkdirSync(dir, { recursive: true });
  const wrapperPath = codexWrapperPath(codexHome, opts.providerId);
  const script = buildWrapperScript(opts);
  const tmp = `${wrapperPath}.${process.pid}.${Date.now()}.tmp`;
  fs.writeFileSync(tmp, script, { mode: 0o700 });
  try {
    fs.renameSync(tmp, wrapperPath);
  } catch (err) {
    try {
      fs.unlinkSync(tmp);
    } catch {
      // best-effort cleanup
    }
    throw err;
  }
  try {
    fs.chmodSync(wrapperPath, 0o700);
  } catch {
    // best-effort; some filesystems may not support chmod
  }
  return wrapperPath;
}

/**
 * Remove the generated wrapper for a provider id. No-op when absent.
 * @returns true when a file was removed.
 */
export function removeCodexAuthWrapper(
  codexHome: string,
  providerId: string,
): boolean {
  const wrapperPath = codexWrapperPath(codexHome, providerId);
  try {
    fs.unlinkSync(wrapperPath);
    return true;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") {
      return false;
    }
    throw err;
  }
}
