// @generated by scripts/sync-model-metadata (npm run sync:model-metadata)
//
// DO NOT EDIT BY HAND. This artifact is a deterministic, byte-stable snapshot
// of the protocol/reasoning enrichment metadata the plugin uses to route
// AxonHub models to the correct OpenClaw `api` adapter and reasoning profile.
//
// It contains only the fields the plugin needs. It never contains
// instance-specific data, credentials, or nondeterministic timestamps. Every
// object and array is sorted so an unchanged upstream source produces
// byte-identical output.
//
// The runtime never fetches the upstream catalog directly; releases stay
// reproducible. The resolver in `model-metadata.ts` consumes this artifact.

import type { AxonhubProtocolFamily } from "./model-types.js";

/** Schema version for the generated artifact. Bump when the shape changes. */
export const MODEL_METADATA_SCHEMA_VERSION = 1 as const;

/**
 * A single enrichment record. Keyed by canonical model id; `owners` narrows the
 * match so ambiguous global ids do not steal routing from the wrong owner.
 */
export type ModelMetadataRecord = {
  /** Canonical, lowercased model id. */
  id: string;
  /** Known alias ids (lowercased, sorted) that map to this record. */
  aliases?: readonly string[];
  /** Owner/`owned_by` values (lowercased, sorted) this record applies to. */
  owners?: readonly string[];
  /** Resolved protocol family. */
  protocolFamily: AxonhubProtocolFamily;
  /** Supported reasoning efforts (sorted by rank), when known. */
  supportedReasoningEfforts?: readonly string[];
  /** Default reasoning effort, when the upstream source specifies one. */
  defaultReasoningEffort?: string;
};

/**
 * Owner-alias groups: AxonHub `owned_by` value → protocol family. Used as a
 * narrow owner-level fallback (precedence step 4) before the conservative
 * OpenAI-compatible default. Sorted by owner for determinism.
 */
export const OWNER_PROTOCOL_FAMILIES: Readonly<
  Record<string, AxonhubProtocolFamily>
> = {
  "anthropic": "anthropic",
  "gemini": "gemini",
  "google": "gemini",
  "google-vertex": "gemini"
};

/**
 * Owner aliases: upstream `owned_by` variants normalized to a canonical owner
 * key used by `OWNER_PROTOCOL_FAMILIES`. Sorted by alias for determinism.
 */
export const OWNER_ALIASES: Readonly<Record<string, string>> = {
  "alibaba-cn": "alibaba",
  "google-vertex": "google",
  "moonshot": "moonshotai",
  "moonshotai-cn": "moonshotai",
  "stepfun-ai": "stepfun",
  "zhipuai": "zai"
};

// Records are sorted by id. Reasoning efforts follow OpenClaw rank order:
// off < minimal < low < medium < high < adaptive < xhigh < max.
export const MODEL_METADATA_RECORDS: readonly ModelMetadataRecord[] = [
  {
    "id": "claude-fable-5",
    "owners": [
      "anthropic"
    ],
    "protocolFamily": "anthropic",
    "supportedReasoningEfforts": [
      "low",
      "medium",
      "high",
      "xhigh",
      "max"
    ]
  },
  {
    "id": "claude-opus-4-6",
    "owners": [
      "anthropic"
    ],
    "protocolFamily": "anthropic",
    "supportedReasoningEfforts": [
      "low",
      "medium",
      "high",
      "max"
    ]
  },
  {
    "id": "claude-opus-4-7",
    "owners": [
      "anthropic"
    ],
    "protocolFamily": "anthropic",
    "supportedReasoningEfforts": [
      "low",
      "medium",
      "high",
      "xhigh",
      "max"
    ]
  },
  {
    "id": "claude-opus-4-8",
    "owners": [
      "anthropic"
    ],
    "protocolFamily": "anthropic",
    "supportedReasoningEfforts": [
      "low",
      "medium",
      "high",
      "xhigh",
      "max"
    ]
  },
  {
    "id": "claude-sonnet-4-6",
    "owners": [
      "anthropic"
    ],
    "protocolFamily": "anthropic",
    "supportedReasoningEfforts": [
      "low",
      "medium",
      "high",
      "max"
    ]
  },
  {
    "id": "claude-sonnet-5",
    "owners": [
      "anthropic"
    ],
    "protocolFamily": "anthropic",
    "supportedReasoningEfforts": [
      "low",
      "medium",
      "high",
      "xhigh",
      "max"
    ]
  },
  {
    "id": "deepseek-v4-flash",
    "owners": [
      "deepseek"
    ],
    "protocolFamily": "openai-completions",
    "supportedReasoningEfforts": [
      "low",
      "medium",
      "high",
      "xhigh",
      "max"
    ]
  },
  {
    "id": "deepseek-v4-pro",
    "owners": [
      "deepseek"
    ],
    "protocolFamily": "openai-completions",
    "supportedReasoningEfforts": [
      "low",
      "medium",
      "high",
      "xhigh",
      "max"
    ]
  },
  {
    "id": "gpt-5.6",
    "owners": [
      "openai"
    ],
    "protocolFamily": "openai-responses",
    "supportedReasoningEfforts": [
      "low",
      "medium",
      "high",
      "xhigh",
      "max"
    ]
  },
  {
    "id": "gpt-5.6-luna",
    "owners": [
      "openai"
    ],
    "protocolFamily": "openai-responses",
    "supportedReasoningEfforts": [
      "low",
      "medium",
      "high",
      "xhigh",
      "max"
    ]
  },
  {
    "id": "gpt-5.6-sol",
    "owners": [
      "openai"
    ],
    "protocolFamily": "openai-responses",
    "supportedReasoningEfforts": [
      "low",
      "medium",
      "high",
      "xhigh",
      "max"
    ]
  },
  {
    "id": "gpt-5.6-terra",
    "owners": [
      "openai"
    ],
    "protocolFamily": "openai-responses",
    "supportedReasoningEfforts": [
      "low",
      "medium",
      "high",
      "xhigh",
      "max"
    ]
  }
];
